# Site settings
title: Full Stack Developer
name: Antonio Bilate
email: abilate@gmail.com
url: https://bilate.github.io/portfolio
description: "A Full stack developer with a passion for architecting applications and lately focused on javascript development."
skills: "Backend - Frontend - Mobile"
meta_author: Bilate Antonio

# Google webmaster tools
google_verify:

# https://ssl.bing.com/webmaster/configure/verify/ownership Option 2 content= goes here
bing_verify:

# Contact form:
# - static : pass through formspree.io to validate email sending
# - disqus : replace contact form by disqus thread
# - comment the line below if you want to stick with the default PHP contact form
contact: static

# Color settings (hex-codes without the leading hash-tag)
color:
  primary: 1D83C1
  primary-rgb: "29,131,193"
  secondary: 505050
  secondary-dark: 292929

# Footer settings
footer:
  social: Find me

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: twitter
    url: https://twitter.com/antoniobilate
  - title: facebook
    url: https://www.facebook.com/antonio.bilate
  - title: linkedin
    url: https://br.linkedin.com/in/antoniobilate


# Build settings
permalink: pretty
baseurl: /portfolio
